# Generated by Django 4.2.7 on 2023-11-23 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updater', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
